# Generated by Django 4.2.16 on 2025-11-02 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="External customer ID from CSV data",
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(18),
                            django.core.validators.MaxValueValidator(120),
                        ]
                    ),
                ),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                (
                    "monthly_salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "approved_limit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Approved credit limit (36 * monthly_salary)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "current_debt",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Sum of all outstanding loan EMIs",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "customers",
                "ordering": ["customer_id"],
                "indexes": [
                    models.Index(
                        fields=["customer_id"], name="customers_custome_b85ebb_idx"
                    ),
                    models.Index(
                        fields=["phone_number"], name="customers_phone_n_7d2329_idx"
                    ),
                ],
            },
        ),
    ]
