# Generated by Django 4.2.16 on 2025-11-02 13:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="External loan ID from CSV data",
                        unique=True,
                    ),
                ),
                (
                    "loan_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tenure",
                    models.IntegerField(
                        help_text="Loan tenure in months",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(600),
                        ],
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Annual interest rate percentage",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "monthly_repayment",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly EMI amount",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "emis_paid_on_time",
                    models.IntegerField(
                        default=0,
                        help_text="Number of EMIs paid on time",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("date_of_approval", models.DateField(help_text="Loan approval date")),
                ("end_date", models.DateField(help_text="Expected loan end date")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "loans",
                "ordering": ["-date_of_approval"],
                "indexes": [
                    models.Index(fields=["loan_id"], name="loans_loan_id_413fca_idx"),
                    models.Index(
                        fields=["customer", "-date_of_approval"],
                        name="loans_custome_76f4ec_idx",
                    ),
                    models.Index(
                        fields=["date_of_approval"], name="loans_date_of_2d31da_idx"
                    ),
                ],
            },
        ),
    ]
